version: '2'

services:

  api:
    restart: always
    build: ./server
    command: /usr/local/bin/gunicorn -w 4 -b 0.0.0.0:8001 wsgi:app
    expose:
      - "8001"
    volumes:
      - .:/api
    env_file:
      - web.env
      - db.env

  postgres:
    restart: always
    image: "postgres:latest"
    env_file:
      - db.env
    ports:
      - "5432:5432"
    volumes:
      - data-postgres:/var/lib/postgresql/data:Z

  client:
    restart: always
    build: ./client
    expose:
      - "8002"
    command: "nginx -g 'daemon off;'"

  nginx:
    restart: always
    build: ./nginx
    ports:
      - "80:80"

volumes:
  data-postgres:
